/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RapidfireRouteImport } from './routes/rapidfire'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as GameRouteImport } from './routes/game'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ContestIndexRouteImport } from './routes/contest.index'
import { Route as ProblemsSlugRouteImport } from './routes/problems.$slug'
import { Route as GameRapidfireRouteImport } from './routes/game_.rapidfire'
import { Route as GameDuelRouteImport } from './routes/game_.duel'
import { Route as ContestIdRouteImport } from './routes/contest.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidfireRoute = RapidfireRouteImport.update({
  id: '/rapidfire',
  path: '/rapidfire',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsRoute,
} as any)
const ContestIndexRoute = ContestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContestRoute,
} as any)
const ProblemsSlugRoute = ProblemsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProblemsRoute,
} as any)
const GameRapidfireRoute = GameRapidfireRouteImport.update({
  id: '/game_/rapidfire',
  path: '/game/rapidfire',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDuelRoute = GameDuelRouteImport.update({
  id: '/game_/duel',
  path: '/game/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestIdRoute = ContestIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/contest': typeof ContestRouteWithChildren
  '/discussion': typeof DiscussionRoute
  '/documents': typeof DocumentsRoute
  '/duel': typeof DuelRoute
  '/galaxy': typeof GalaxyRoute
  '/game': typeof GameRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rapidfire': typeof RapidfireRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/contest/$id': typeof ContestIdRoute
  '/game/duel': typeof GameDuelRoute
  '/game/rapidfire': typeof GameRapidfireRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/contest/': typeof ContestIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/discussion': typeof DiscussionRoute
  '/documents': typeof DocumentsRoute
  '/duel': typeof DuelRoute
  '/galaxy': typeof GalaxyRoute
  '/game': typeof GameRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rapidfire': typeof RapidfireRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/contest/$id': typeof ContestIdRoute
  '/game/duel': typeof GameDuelRoute
  '/game/rapidfire': typeof GameRapidfireRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/contest': typeof ContestIndexRoute
  '/problems': typeof ProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/contest': typeof ContestRouteWithChildren
  '/discussion': typeof DiscussionRoute
  '/documents': typeof DocumentsRoute
  '/duel': typeof DuelRoute
  '/galaxy': typeof GalaxyRoute
  '/game': typeof GameRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rapidfire': typeof RapidfireRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/contest/$id': typeof ContestIdRoute
  '/game_/duel': typeof GameDuelRoute
  '/game_/rapidfire': typeof GameRapidfireRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/contest/': typeof ContestIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/certificates'
    | '/chat'
    | '/contest'
    | '/discussion'
    | '/documents'
    | '/duel'
    | '/galaxy'
    | '/game'
    | '/interview'
    | '/login'
    | '/problems'
    | '/profile'
    | '/rapidfire'
    | '/redeem'
    | '/register'
    | '/contest/$id'
    | '/game/duel'
    | '/game/rapidfire'
    | '/problems/$slug'
    | '/contest/'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/certificates'
    | '/chat'
    | '/discussion'
    | '/documents'
    | '/duel'
    | '/galaxy'
    | '/game'
    | '/interview'
    | '/login'
    | '/profile'
    | '/rapidfire'
    | '/redeem'
    | '/register'
    | '/contest/$id'
    | '/game/duel'
    | '/game/rapidfire'
    | '/problems/$slug'
    | '/contest'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/certificates'
    | '/chat'
    | '/contest'
    | '/discussion'
    | '/documents'
    | '/duel'
    | '/galaxy'
    | '/game'
    | '/interview'
    | '/login'
    | '/problems'
    | '/profile'
    | '/rapidfire'
    | '/redeem'
    | '/register'
    | '/contest/$id'
    | '/game_/duel'
    | '/game_/rapidfire'
    | '/problems/$slug'
    | '/contest/'
    | '/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  CertificatesRoute: typeof CertificatesRoute
  ChatRoute: typeof ChatRoute
  ContestRoute: typeof ContestRouteWithChildren
  DiscussionRoute: typeof DiscussionRoute
  DocumentsRoute: typeof DocumentsRoute
  DuelRoute: typeof DuelRoute
  GalaxyRoute: typeof GalaxyRoute
  GameRoute: typeof GameRoute
  InterviewRoute: typeof InterviewRoute
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RapidfireRoute: typeof RapidfireRoute
  RedeemRoute: typeof RedeemRoute
  RegisterRoute: typeof RegisterRoute
  GameDuelRoute: typeof GameDuelRoute
  GameRapidfireRoute: typeof GameRapidfireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapidfire': {
      id: '/rapidfire'
      path: '/rapidfire'
      fullPath: '/rapidfire'
      preLoaderRoute: typeof RapidfireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/contest/': {
      id: '/contest/'
      path: '/'
      fullPath: '/contest/'
      preLoaderRoute: typeof ContestIndexRouteImport
      parentRoute: typeof ContestRoute
    }
    '/problems/$slug': {
      id: '/problems/$slug'
      path: '/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof ProblemsSlugRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/game_/rapidfire': {
      id: '/game_/rapidfire'
      path: '/game/rapidfire'
      fullPath: '/game/rapidfire'
      preLoaderRoute: typeof GameRapidfireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game_/duel': {
      id: '/game_/duel'
      path: '/game/duel'
      fullPath: '/game/duel'
      preLoaderRoute: typeof GameDuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$id': {
      id: '/contest/$id'
      path: '/$id'
      fullPath: '/contest/$id'
      preLoaderRoute: typeof ContestIdRouteImport
      parentRoute: typeof ContestRoute
    }
  }
}

interface ContestRouteChildren {
  ContestIdRoute: typeof ContestIdRoute
  ContestIndexRoute: typeof ContestIndexRoute
}

const ContestRouteChildren: ContestRouteChildren = {
  ContestIdRoute: ContestIdRoute,
  ContestIndexRoute: ContestIndexRoute,
}

const ContestRouteWithChildren =
  ContestRoute._addFileChildren(ContestRouteChildren)

interface ProblemsRouteChildren {
  ProblemsSlugRoute: typeof ProblemsSlugRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsSlugRoute: ProblemsSlugRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  CertificatesRoute: CertificatesRoute,
  ChatRoute: ChatRoute,
  ContestRoute: ContestRouteWithChildren,
  DiscussionRoute: DiscussionRoute,
  DocumentsRoute: DocumentsRoute,
  DuelRoute: DuelRoute,
  GalaxyRoute: GalaxyRoute,
  GameRoute: GameRoute,
  InterviewRoute: InterviewRoute,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RapidfireRoute: RapidfireRoute,
  RedeemRoute: RedeemRoute,
  RegisterRoute: RegisterRoute,
  GameDuelRoute: GameDuelRoute,
  GameRapidfireRoute: GameRapidfireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
